language: objective-c
osx_image: xcode11.6

before_install:
    - brew update
    - brew outdated xctool || brew upgrade xctool
    - cd OneDriveSDK && pod install

script: 
    - xcodebuild build test -workspace OneDriveSDK.xcworkspace -scheme OneDriveSDKTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8'
